---

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/fileserver"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dependencies"
  # Add more environments like pip and docker
