sudo: false
# Must set language to python so we can install custom python pacakges in
# docker-based travis builds
language: python
python:
- "3.7"
services:
- mysql
compiler:
- gcc
addons:
  apt:
    packages:
    - valac
    - uuid-dev
    - libevent-dev
    - libarchive-dev
    - intltool
    - libjansson-dev
    - libonig-dev
    - libfuse-dev
    - net-tools
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.ccache"
before_install:
- ccache -s
- export PATH=/usr/lib/ccache:${PATH}
install:
- "./ci/install-deps.sh"
script:
- "./ci/run.py"
notifications:
  slack:
    rooms:
      secure: 3H6mh5PPPKo0wuwzZybDwnHOya0/IiW8jn/g9ZUFna5P5IqmuuFacZi+lS5Ffgrv/vRYbv9ebjDvIApk2CDc0KzA2vUwr79BjlfPqm1buf75dPf1aINhNjMT1g16afyxciMbdV5QtzSoiyYn+P4026SU40jmJXGL2u/O01HH/dF8Aw8/rpWjhZp1PjhRC40iilVe/q38E9biGsi9lKzJVXumhm3IYyZLsH7aqr2rTg67U1j2bB8OwTaJx4vZdpf6gxKLpwrumkLT1lNFvhOYieuxqNvBw752bB++FImswCwZ2t9ejX2jW1GjTdIJ1FpkHEVF2cz9AeRL5xeBz4bHtG3490PpfqcPLjQ39MI/FP6QRupAi0EUufbHpfx30kdqqBEyztcF66vR4hA42uDopIoF0HIIFyzgTnmN5SKmyhmOaE+hmfgWNtCm79ZYEx/PB8BvUyR2IV6UvQy2kHznNk8UnDnO2shP/2sOn3IUvZQ99y0UUk5LmJMQNOCiB31N1AFESbVKzAqR4ZKN+5K7CwEUQ1uaJgMmwuutrpgR+x6QvN3+zPHiLLunx6zTAJW6PWiHx5+Gxzt2Xi8iEtsmBOWu4o5kvAkjFMtYlzgd+12waQm4HpZaJ+xMbnZEG0jR3CUn7pXjKZhTxiFgXunYkalKWIIITFF5YUWgQJVrfng=
    on_success: change
    on_failure: always
